export const QUIZ_RESULTS_SEND_REQUEST = 'QUIZ_RESULTS_SEND_REQUEST'
export const QUIZ_RESULTS_SEND_SUCCESS = 'QUIZ_RESULTS_SEND_SUCCESS'
export const QUIZ_RESULTS_SEND_FAILURE = 'QUIZ_RESULTS_SEND_FAILURE'
